### ISSUE TITLE
hardcoded path in settings.gradle

### ISSUE THREAD

**Issue by jmfayard** [GetStream/WhatsApp-Clone-Android#1]
Hello @tschellenbach

I'm not sure whether it's necessary, but this part of the build is unlikely to work on another computer :)

```
// settings.gradle
project(":chat").projectDir=new File("/Users/thierry/workspace/android2/library")
```

**Comment by tschellenbach** [comment]
Whoops, this is a leftover (had to make some small edits to stream android chat lib while writing this tutorial). I've commented out those lines.
