### ISSUE TITLE
what database ?

### ISSUE THREAD

**Issue by meetgyn** [GetStream/WhatsApp-Clone-Android#10]
what database does this app use? I'm new to mobile dev, I'm trying to learn on my own

**Comment by zsmb13** [comment]
Hi! This is an old sample, for an up-to-date chat SDK, take a look at the [GetStream/stream-chat-android](https://github.com/GetStream/stream-chat-android/) repo, specifically the [stream-chat-android-offline](https://github.com/GetStream/stream-chat-android/tree/main/stream-chat-android-offline) module. That uses [Room](https://developer.android.com/training/data-storage/room) as its database.
