### ISSUE TITLE
Error While trying to install the app through android studio

### ISSUE THREAD

**Issue by DhirajG** [GetStream/WhatsApp-Clone-Android#4]
When I do not update the app to gradle plugin to 5.6.4. IT gives me an error. 
Installation did not succeed.
The application could not be installed: INSTALL_PARSE_FAILED_NO_CERTIFICATES
APK signature verification failed.

If I create a signed apk I am able to do so. But When I try to install the signed apk it gives me Parse Error. 

When I update the plugin to 5.6.4/ It gives me error 
AAPT: error: resource attr/flow vertical Separator not found. 15 such errors of missing.

**Comment by the-code-chef** [comment]
Use 2.0.0-beta4 in constrain layout.
minSDkVersion is 29. Make sure you run in device which should have 29 version. Downgrade it if you don't have

**Comment by tschellenbach** [comment]
Yup android studio + Constraint layout beta 2 had an issue.
